### ISSUE TITLE
Online and offline events not fired

### ISSUE THREAD

**Issue by blupu** [uncatcrea/wp-app-kit#13]
It appears that binding online and offline events doesn't work in functions.js. After a bit of search and help from the PGB support, the following minimal app works.

```
<!DOCTYPE html>
<html>
	<head>
		<script src="phonegap.js"></script>

        <script type="text/javascript">        

            function onLoad(){
                document.addEventListener("deviceready", onDeviceReady, false);
                document.addEventListener("online", onOnline, false);
                document.addEventListener("offline", onOffline, false);
            }

            function onDeviceReady() {
                 alert('device is ready');
            }

            function onOnline(){
                alert('Device is Online');
            }

            function onOffline(){
                alert('Device is Offline');
            }
            
        </script>

    </head>
	<body onload="onLoad()">
        Testing PGB solution
    </body>
</html>
```

We should implement that in the core and provide theme events to access offline and online events.

**Comment by blupu** [comment]
Mathieu, does your implementation of online/offline events in core resolves that case?

**Comment by mleroi** [comment]
Yes that is supported now withe the 2 events : network:online and 'network:offline'

Commented example in bootstrap theme : 

App.on( 'network:online', function(event) {
	 $( '#feedback' ).removeClass( 'error' ).html( "Internet connexion ok :)" ).slideDown();
} );
	 
App.on( 'network:offline', function(event) {
	 $( '#feedback' ).addClass( 'error' ).html( "Internet connexion lost :(" ).slideDown();
} );
